### ISSUE TITLE
Заполнить вопросы

### ISSUE THREAD

**Issue by blayzzand-st** [JeJutic/sup-interactive#15]
**Задание:**
Необходимо заполнить имеющиеся шаблоны Default Question текстом. Всего подразумевается 3 варианта заданий:
1) Выбрать один вариант ответа из 4-х (текст)
2) Выбрать один вариант ответа из 4-х (картинка)
3) Ввести свой ответ

Будет документ, в котором прописаны названия вопросов, их описания, варианты ответов и верный ответ. Все это нужно подставить в свой шаблон для каждого моста
UPD: Задание взято

**Когда можно делать:**
После появления документа с текстовым описанием всех вопросов

**Comment by JeJutic** [comment]
Сегодня планирую сделать, если никто не берет
