### ISSUE TITLE
Сделать страницу завершения

### ISSUE THREAD

**Issue by JeJutic** [JeJutic/sup-interactive#3]
**Задание:**
Компонент страницы завершения готов, необходимо застилизовать его
Пока что можно применить такие же стили, как и к приветственной странице
В конце просто немного подредактируем

**Когда можно делать:**
Уже сейчас, ближе к завершению проекта надо будет заменить текст и, возможно, добавить какие-нибудь графические элементы

**Ссылки:**
[Дизайн](https://www.figma.com/file/3dWcXjSWTEfi32JAvmmjzN/Дизайн?node-id=8%3A13218&mode=dev)
[FinishScreen](https://github.com/JeJutic/sup-interactive/blob/master/src/commons/FinishScreen.jsx)

**Comment by piece-of-tart** [comment]
Беру на себя
