### ISSUE TITLE
Возможно добавить функциональность, связанную с геопозицией

### ISSUE THREAD

**Issue by JeJutic** [JeJutic/sup-interactive#5]
**Задание:**
Реализовать рабочие подсказки в зависимости от местоположения пользователя
Можно предлагать ближаший мост с не сделанным заданием.
Можно просто отображать маркер с позицией.

**Когда можно делать:**
Сейчас

**Ссылки:**
[Полезный пример из документации react-leaflet](https://react-leaflet.js.org/docs/example-events/)

**Comment by murysinm** [comment]
возьму это задание
