### ISSUE TITLE
Добавление анимаций question card

### ISSUE THREAD

**Issue by blayzzand-st** [JeJutic/sup-interactive#9]
Сделать анимации для question card. Конкретно для:
1) **Появление карточки** (слайд снизу до исходного положения)
2) **Закрытия карточки** по кнопке х (слайд из исходного положения вниз)
3) **Поворот карточки** в обоих положениях (card и card-reverse); поворот на 360deg, с изменением класса card на card-reverse и наоборот

**Comment by ablearthy** [comment]
Го разберусь с этой штукой (добавьте меня в assignees, чтобы не было ситуации, что два человека работают над одним и тем же)
